inicio tela de registro de funcionarios
BrunoBross/A1A-Car-Wash pull request #2
Opened 2022-10-04 04:40 UTC by BrunoBross

2022-10-04 21:54 UTC, BrunoBross commented on package/app/client/modules/registeremployee/RegisterEmployeeComponent.py
> +    def registerEmployee(self, username: str, fullname: str, password: str, salary: str):
@PedroBinotto como eu posso melhorar esses IFs?

2022-10-04 23:33 UTC, PedroBinotto requested changes

2022-10-04 23:33 UTC, PedroBinotto commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
dá um ignore no `.idea/`... vai dar conflito com o resto da galera

2022-10-04 23:33 UTC, PedroBinotto commented on package/app/api/modules/user/UserService.py
> +from colorama import Fore
kkkk que porra eh colorama

2022-10-04 23:33 UTC, PedroBinotto commented on package/app/api/modules/user/UserService.py
> +
mano isso aqui tem que ir pra um employee service, num modulo separado, nao pro user

2022-10-04 23:33 UTC, PedroBinotto commented on package/app/api/modules/user/UserQuery.py
> +    def createEmployee(self, username: str, fullname: str, password: str, salary: str):
separa e move pra modulo employee

2022-10-04 23:33 UTC, PedroBinotto commented on package/app/api/modules/user/UserDtoMapper.py
> +
se tu vai mandar as coisas pra outro modulo, isso aqui acho que vai junto

2022-10-04 23:33 UTC, PedroBinotto commented on package/app/client/layout/sidebar.py
> +    "Cadastrar Funcionários": SidebarItem(
"Cadastrar Funcionários" -> "Cadastrar Funcionário", não acha?

2022-10-04 23:33 UTC, PedroBinotto commented on package/app/client/modules/registeremployee/RegisterEmployeeComponent.py
> +        self.__userService = UserService()
Component conversa com Controller, nao service... e acho que seria o de employee, nao user

2022-10-04 23:33 UTC, PedroBinotto commented on package/app/client/modules/registeremployee/RegisterEmployeeComponent.py
> +    def registerEmployee(self, username: str, fullname: str, password: str, salary: str):
alguns da pra pegar ja no GTK, os demais tu passa pra uma classe validator separada, e ainda assim dá pra fazer com regex e afins pra dar uma melhoradinha

2022-10-04 23:33 UTC, PedroBinotto commented on package/app/client/modules/registeremployee/RegisterEmployeeView.py
> +        self.__state = ComponentState()
o state a gente vai mover pro component... da pra evitar aquela cagadinha que tava rolando no meu login la dae

2022-10-04 23:40 UTC, BrunoBross commented on package/app/api/modules/user/UserService.py
> +from colorama import Fore
ja apaguei kkkkkkkkkkkkkkk

2022-10-05 18:50 UTC, PedroBinotto approved these changes
topzera

2022-10-05 18:50 UTC, merged